# Generated by Django 2.1.5 on 2019-02-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_forget_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forget_password',
        ),
    ]
