# Generated by Django 2.1.5 on 2019-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_delete_forget_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('class1', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
            ],
        ),
    ]
