# Generated by Django 2.1.5 on 2019-02-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enroll',
            field=models.IntegerField(),
        ),
    ]
